/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'text-primary': '#131515',
        'text-secondary': '#494D4D',
        'text-inverse': '#FFFFFF',
        'surface-base': '#F2F2F2',
        'surface-raised': '#FFFFFF',
        'brand-primary': '#7E1514',
        'brand-secondary': '#F2F2F2',
        'brand-accent': '#E8C424',
        'brand-blue': '#7E1514',
        'brand-purple': '#7E1514',
        'brand-green': '#12A70A',
        'brand-red': '#7E1514',
        'brand-black': '#000000',
        'brand-offwhite': '#F2F2F2',
        'black': '#000000',
        'white': '#FFFFFF',
        'base-100': '#f0f0f0',
        'base-200': '#ffffff',
        'base-300': '#F2F2F2',
        'base-content': '#0A0A0A',
        'neutral': '#222222',
        'neutral-content': '#FFFFFF',
        'primary': '#FF0F67',
        'primary-content': '#fff',
        'secondary': '#FFF07C',
        'secondary-content': '#0A0A0A',
        'accent': '#439775',
        'accent-content': '#0A0A0A',
        'info': '#3ABFF8',
        'success': '#36D399',
        'warning': '#FBBD23',
        'error': '#F87272',
        'highlight': '#454ADE',
        'muted': '#777777',
      },
      fontFamily: {
        sans: ['"Inter Tight"', '"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'xs': '12px',
        'sm': '14px',
        'md': '15px',
        'lg': '16px',
        'xl': '18px',
        '2xl': '22px',
        '3xl': '24px',
        '4xl': '34px',
      },
      spacing: {
        's1': '12px',
        's2': '16px',
        's3': '28px',
        's4': '34px',
      },
      borderRadius: {
        'xs': '16px',
        'sm': '20px',
        'md': '50px',
        'lg': '100px',
      },
      boxShadow: {
        'shadow-1': 'rgba(19, 21, 21, 0.5) 0px 4px 10px 0px, rgba(19, 21, 21, 0.5) 0px 10px 35px 0px',
        'shadow-2': 'rgba(19, 21, 21, 0.05) 0px 8px 20px 0px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'slide-up': 'slideUp 0.5s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
